
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = false
decorations = "full"
title = "selene@gaia"
opacity = 1
decorations_theme_variant = "Dark"

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'
# storm
# background = '#24283b'
# foreground = '#c0caf5'

[colors.cursor]
cursor = '#faf0fb'
text = '#24283b'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'
# storm
# black = '#1d202f'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'
# storm
# black = '#414868'
# red = '#ff899d'
# green = '#9fe044'
# yellow = '#faba4a'
# blue = '#8db0ff'
# magenta = '#c7a9ff'
# cyan = '#a4daff'
# white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[colors]
draw_bold_text_with_bright_colors = false

# [colors.primary]
# background = "0x2E3440"
# foreground = "0xD8DEE9"
#
# [colors.normal]
# black = "0x3B4252"
# red = "0xBF616A"
# green = "0xA3BE8C"
# yellow = "0xEBCB8B"
# blue = "0x81A1C1"
# magenta = "0xB48EAD"
# cyan = "0x88C0D0"
# white = "0xE5E9F0"
#
# [colors.bright]
# black = "0x4C566A"
# red = "0xBF616A"
# green = "0xA3BE8C"
# yellow = "0xEBCB8B"
# blue = "0x81A1C1"
# magenta = "0xB48EAD"
# cyan = "0x8FBCBB"
# white = "0xECEFF4"

[font]
size = 18

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Medium"

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Underline"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
