# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

env = AQ_DRM_DEVICES,/dev/dri/card0
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = HYPRCURSOR_SIZE,24
env = LD_PRELOAD,
env = MOZ_DISABLE_RDD_SANDBOX,1
env = MOZ_ENABLE_WAYLAND,1 
env = PROTON_ENABLE_WAYLAND,1
env = PULSE_LATENCY_MSEC,60
env = QT_AUTO_SCREEN_SCALE_FACTOR,
env = QT_CURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1 
env = XCURSOR_SIZE,24

# reduce lantency
env = MESA_VK_WSI_PRESENT_MODE,immediate
env = KWIN_DRM_NO_AMS,1
env = PROTON_USE_NTSYNC,1
env = PROTON_ENABLE_WAYLAND,1

# nvidia
env = CLUTTER_BACKEND,wayland
env = EGL_PLATFORM,wayland
env = GBM_BACKEND,nvidia-drm
env = GDK_BACKEND,wayland,x11,*
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
env = SDL_VIDEODRIVER,wayland
env = SDL_VIDEO_DRIVER,wayland
env = WLR_DRM_NO_ATOMIC,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = __GL_VRR_ALLOWED,1
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __NV_DISABLE_EXPLICIT_SYNC,0
env = __NV_PRIME_RENDER_OFFLOAD,1
env = __VK_LAYER_NV_optimus,NVIDIA_only
